month="october"
print(month[3:6])
month="october"
print(month.find("tober"))
month="october"
print(len(month))
month="october"
print(october.upper())
month="october"
print(october.lower())
month="october"
print(october+october)
